# What is the goal of your workflow
# Goal: Whenever someone chnages the python code, 
# the liner will check if the sysntax, format, indentation (linting) is correct or not


name: Auto Linter

on: 
  push:
    paths: "*.py"


jobs:
  code-linting:
    runs-on: ubuntu-latest
    # this step will automatically clone the code of the current branch into the runner
    steps:
        # run: instead of the run you have => uses: 
        # to clone the code to ubuntu-latest vm ephemal container
        # run: git clone url but not using this
      - name: Checkout/clone the code
        uses: actions/checkout@v7

      #this step will install python
      - name: Install Python & setuo
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' # Specify your desired version here

      # this step will install the linting toool
      - name: Install Linter
        run: pip install ruff

      # this steps will run the linter
      - name: Check the files for linting
        run: ruff check .
        
        


        
